fixing yaml file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,36 +6,35 @@ jobs:
     working_directory: /go/src/github.com/daghan/invoicer-chapter2
     docker:
       - image: circleci/golang:1.10
-    
     steps:
       - checkout
       - setup_remote_docker
 
-    - run:
-        name: Setup environment
-        command: |
-          gb="/src/github.com/${CIRCLE_PROJECT_USERNAME}";
-          if [ ${CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then
-            dr="securingdevops"
-          else
-            dr=$DOCKER_USER
-          fi
-          cat >> $BASH_ENV << EOF
-          export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"
-          export GOPATH_BASE="$(echo ${GOPATH}|cut -d ':' -f 1)${gb}"
-          export DOCKER_REPO="$dr"
-          EOF
-    - run: mkdir -p "${GOPATH_BASE}"
-    - run: mkdir -p "${GOPATH_HEAD}/bin"
-    - run: go get github.com/govend/govend
+      - run:
+          name: Setup environment
+          command: |
+            gb="/src/github.com/${CIRCLE_PROJECT_USERNAME}";
+            if [ ${CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then
+              dr="securingdevops"
+            else
+              dr=$DOCKER_USER
+            fi
+            cat >> $BASH_ENV << EOF
+            export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"
+            export GOPATH_BASE="$(echo ${GOPATH}|cut -d ':' -f 1)${gb}"
+            export DOCKER_REPO="$dr"
+            EOF
+      - run: mkdir -p "${GOPATH_BASE}"
+      - run: mkdir -p "${GOPATH_HEAD}/bin"
+      - run: go get github.com/govend/govend
 
-    - run:
-        name: Testing application
-        command: |
-          go test \
-          github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
+      - run:
+          name: Testing application
+          command: |
+            go test \
+            github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
 
-    - run:
+      - run:
         name: Build application container
         command: |
           go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
@@ -43,30 +42,30 @@ jobs:
           cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
           docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
 
-    - run:
-        name: Run application in background
-        command: |
-          docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
-        background: true
+      - run:
+          name: Run application in background
+          command: |
+            docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
+          background: true
 
-    - run:
-        name: ZAP baseline test of application
-        # Only fail on error code 1, which indicates at least one FAIL was found.
-        # error codes 2 & 3 indicate WARN or other, and should not break the run
-        command: |
-          (
-          docker pull owasp/zap2docker-weekly && \
-          docker run -t owasp/zap2docker-weekly zap-baseline.py \
-              -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
-              -t http://172.17.0.2:8080/ || \
-          if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-          )
+      - run:
+          name: ZAP baseline test of application
+          # Only fail on error code 1, which indicates at least one FAIL was found.
+          # error codes 2 & 3 indicate WARN or other, and should not break the run
+          command: |
+            (
+            docker pull owasp/zap2docker-weekly && \
+            docker run -t owasp/zap2docker-weekly zap-baseline.py \
+                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
+                -t http://172.17.0.2:8080/ || \
+            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+            )
 
-    - run:
-        name: Test dependencies are up to date
-        command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'
+      - run:
+          name: Test dependencies are up to date
+          command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'
 
-    - deploy:
+      - deploy:
         # Push application container to dockerhub
         command: |
           if [ "${CIRCLE_BRANCH}" == "master" ]; then
